In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Galaxy200-[Differentially_Methylated_Positions].bed", sep="\t")
df

         chr      start        end       names      pval      qval
0       chr1    1268793    1268793  cg00002593  0.001784  0.230238
1       chr6  147124996  147124996  cg00004963  0.003342  0.310830
2       chr2  240404783  240404783  cg00007426  0.001887  0.237170
3       chr2   38710172   38710172  cg00008800  0.000534  0.132411
4       chr4    1615272    1615272  cg00010108  0.001520  0.214507
...      ...        ...        ...         ...       ...       ...
10449  chr17   46628225   46628225  cg27656658  0.000031  0.054371
10450  chr13  110777186  110777186  cg27657439  0.001512  0.214132
10451   chr4    1201316    1201316  cg27660248  0.000451  0.122866
10452  chr19   21666099   21666099  cg27663389  0.003769  0.326929
10453   chr2    3262407    3262407  cg27665397  0.004756  0.361729

[10454 rows x 6 columns]

In [10]:
#!pip uninstall fireducks -y
#!pip install pyensembl

In [4]:
from pyensembl import EnsemblRelease

# release 77 uses human reference genome GRCh38
data = EnsemblRelease(77)

In [5]:
#%%bash
#pyensembl install --release 77 --species homo_sapiens

2024-11-15 15:10:09,196 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=77, species='homo_sapiens')
2024-11-15 15:10:09,650 - pyensembl.sequence_data - INFO - Loaded sequence dictionary from /home/ubuntu/.cache/pyensembl/GRCh38/ensembl77/Homo_sapiens.GRCh38.cdna.all.fa.gz.pickle
2024-11-15 15:10:09,713 - pyensembl.sequence_data - INFO - Loaded sequence dictionary from /home/ubuntu/.cache/pyensembl/GRCh38/ensembl77/Homo_sapiens.GRCh38.ncrna.fa.gz.pickle
2024-11-15 15:10:09,812 - pyensembl.sequence_data - INFO - Loaded sequence dictionary from /home/ubuntu/.cache/pyensembl/GRCh38/ensembl77/Homo_sapiens.GRCh38.pep.all.fa.gz.pickle

In [6]:
#%%bash
#pyensembl install --release 75 --species homo_sapiens

2024-11-15 15:10:10,440 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=75, species='homo_sapiens')
2024-11-15 15:10:10,918 - pyensembl.sequence_data - INFO - Loaded sequence dictionary from /home/ubuntu/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz.pickle
2024-11-15 15:10:10,971 - pyensembl.sequence_data - INFO - Loaded sequence dictionary from /home/ubuntu/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz.pickle
2024-11-15 15:10:11,078 - pyensembl.sequence_data - INFO - Loaded sequence dictionary from /home/ubuntu/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz.pickle

In [7]:
df

         chr      start        end       names      pval      qval
0       chr1    1268793    1268793  cg00002593  0.001784  0.230238
1       chr6  147124996  147124996  cg00004963  0.003342  0.310830
2       chr2  240404783  240404783  cg00007426  0.001887  0.237170
3       chr2   38710172   38710172  cg00008800  0.000534  0.132411
4       chr4    1615272    1615272  cg00010108  0.001520  0.214507
...      ...        ...        ...         ...       ...       ...
10449  chr17   46628225   46628225  cg27656658  0.000031  0.054371
10450  chr13  110777186  110777186  cg27657439  0.001512  0.214132
10451   chr4    1201316    1201316  cg27660248  0.000451  0.122866
10452  chr19   21666099   21666099  cg27663389  0.003769  0.326929
10453   chr2    3262407    3262407  cg27665397  0.004756  0.361729

[10454 rows x 6 columns]

In [8]:
data75 = EnsemblRelease(75)

In [31]:
all_genes = []
for row in df.iterrows():
    chr = row[1]["chr"].replace("chr", "")
    s_pos = int(row[1]["start"])
    gene_names = data75.gene_names_at_locus(contig=chr, position=s_pos)
    all_genes.append(",".join(gene_names))

df["genes"] = all_genes
df

,chr,start,end,names,pval,qval,genes
0,chr1,1268793,1268793,cg00002593,0.001784,0.230238,TAS1R3
1,chr6,147124996,147124996,cg00004963,0.003342,0.310830,ADGB
2,chr2,240404783,240404783,cg00007426,0.001887,0.237170,
3,chr2,38710172,38710172,cg00008800,0.000534,0.132411,AC016995.3
4,chr4,1615272,1615272,cg00010108,0.001520,0.214507,
...,...,...,...,...,...,...,...
10449,chr17,46628225,46628225,cg27656658,0.000031,0.054371,"HOXB-AS1,HOXB-AS3,HOXB3"
10450,chr13,110777186,110777186,cg27657439,0.001512,0.214132,
10451,chr4,1201316,1201316,cg27660248,0.000451,0.122866,SPON2
10452,chr19,21666099,21666099,cg27663389,0.003769,0.326929,CTD-2561J22.3
10453,chr2,3262407,3262407,cg27665397,0.004756,0.361729,TSSC1

In [32]:
df[df["genes"] == "SEPT9"]

        chr     start       end       names      pval      qval  genes
1280  chr17  75369228  75369228  cg02884239  0.001839  0.233945  SEPT9
1675  chr17  75369219  75369219  cg03804136  0.000664  0.146034  SEPT9
2911  chr17  75368903  75368903  cg06848185  0.000828  0.161477  SEPT9
5084  chr17  75369658  75369658  cg12783819  0.000016  0.054172  SEPT9
6117  chr17  75369224  75369224  cg15044248  0.000771  0.155989  SEPT9
6139  chr17  75290967  75290967  cg15096327  0.000238  0.093417  SEPT9
6725  chr17  75369056  75369056  cg16779463  0.001812  0.232322  SEPT9
6899  chr17  75369091  75369091  cg17300544  0.000032  0.054371  SEPT9
7627  chr17  75369052  75369052  cg19554255  0.000210  0.088554  SEPT9
7900  chr17  75369485  75369485  cg20275528  0.000004  0.054172  SEPT9
8401  chr17  75282777  75282777  cg21678736  0.002546  0.273065  SEPT9

In [33]:
chr_SEPT9 = "chr17"
start_SEPT9 = 75277581 #75277618
end_SEPT9 = 75496678 #75494740
# chr17:77,280,569-77,500,596
# chr17:75277581-75496678 https://www.genecards.org/cgi-bin/carddisp.pl?gene=SEPTIN9

df_SEPT9= df[(df["chr"] == chr_SEPT9) & (df["start"] > start_SEPT9) & (df["end"] < end_SEPT9)]
df_SEPT9 = df_SEPT9.sort_values(by=["start"])
df_SEPT9

,chr,start,end,names,pval,qval,genes
8401,chr17,75282777,75282777,cg21678736,0.002546,0.273065,SEPT9
6139,chr17,75290967,75290967,cg15096327,0.000238,0.093417,SEPT9
2911,chr17,75368903,75368903,cg06848185,0.000828,0.161477,SEPT9
7627,chr17,75369052,75369052,cg19554255,0.000210,0.088554,SEPT9
6725,chr17,75369056,75369056,cg16779463,0.001812,0.232322,SEPT9
6899,chr17,75369091,75369091,cg17300544,0.000032,0.054371,SEPT9
1675,chr17,75369219,75369219,cg03804136,0.000664,0.146034,SEPT9
6117,chr17,75369224,75369224,cg15044248,0.000771,0.155989,SEPT9
1280,chr17,75369228,75369228,cg02884239,0.001839,0.233945,SEPT9
7900,chr17,75369485,75369485,cg20275528,0.000004,0.054172,SEPT9
5084,chr17,75369658,75369658,cg12783819,0.000016,0.054172,SEPT9
2252,chr17,75369940,75369940,cg05184938,0.000107,0.069273,"RP11-936I5.1,SEPT9"

In [39]:
sorted_df = df.sort_values(by=["chr", "qval"], ascending=True)
sorted_df

       chr      start        end       names      pval      qval   genes
81    chr1  223538380  223538380  cg00172597  0.000013  0.054172
687   chr1  240118351  240118351  cg01567173  0.000015  0.054172
1558  chr1    2801150    2801150  cg03543952  0.000009  0.054172
1586  chr1   24229582   24229582  cg03611151  0.000015  0.054172    CNR2
2131  chr1    9099298    9099298  cg04885068  0.000021  0.054172  SLC2A5
...    ...        ...        ...         ...       ...       ...     ...
1005  chrX   47521427   47521427  cg02263204  0.009998  0.495734
3312  chrX   13588175   13588175  cg07810164  0.010114  0.497987   EGFL6
6311  chrX  119868737  119868737  cg15600969  0.010190  0.499198
1409  chrX   35937779   35937779  cg03176466  0.010219  0.499493
889   chrY    6777855    6777855  cg02002345  0.008763  0.468939

[10454 rows x 7 columns]

In [40]:
sorted_df[sorted_df["genes"] == ""]

        chr      start        end       names      pval      qval genes
81     chr1  223538380  223538380  cg00172597  0.000013  0.054172
687    chr1  240118351  240118351  cg01567173  0.000015  0.054172
1558   chr1    2801150    2801150  cg03543952  0.000009  0.054172
3360   chr1   76080727   76080727  cg07923233  0.000006  0.054172
10027  chr1   17475832   17475832  cg26516532  0.000015  0.054172
...     ...        ...        ...         ...       ...       ...   ...
10389  chrX   55101327   55101327  cg27492220  0.009638  0.488387
1005   chrX   47521427   47521427  cg02263204  0.009998  0.495734
6311   chrX  119868737  119868737  cg15600969  0.010190  0.499198
1409   chrX   35937779   35937779  cg03176466  0.010219  0.499493
889    chrY    6777855    6777855  cg02002345  0.008763  0.468939

[2688 rows x 7 columns]

In [46]:
gene_names = data75.gene_names_at_locus(contig=1, position=240118351)
gene_names

[]

In [47]:
sorted_df.to_csv("DMP_genes.csv", sep="\t", index=None)